"""initial migration

Revision ID: 20015c34c982
Revises: 
Create Date: 2025-06-29 12:45:21.601511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20015c34c982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
