"""Initial migration

Revision ID: 8d6cd96304f7
Revises: 5b2837825015
Create Date: 2025-06-24 12:13:02.434589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d6cd96304f7'
down_revision = '5b2837825015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('orders_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('total')
        batch_op.drop_column('items')
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###
